### ISSUE TITLE
Hi, I just wonder how am I supposed to use bootstrap in gulp-front? 

### ISSUE THREAD

**Issue by TakanaNoHana** [zoxon/gulp-front#53]
Do I need to change from Stylus to Sass? Sorry if the question is silly, I'm very new to this.

**Comment by zoxon** [comment]
Hi. For Sass support you need add task for compile sass files.
Some time ago another developer was already asking about this. 
[#52 Question: Stylus to Sass](https://github.com/zoxon/gulp-front/issues/52)

**Comment by TakanaNoHana** [comment]
Thanks for replying. I saw the question but the solution wasn't what I looked for. I don't want to lose the CSS framework gulp-front has, and I has taken a liking to Stylus, I want to keep using it instead of replacing with Sass.  So I wonder if I can add tasks for compiling sass files but keep using Stylus at the same time?

**Comment by zoxon** [comment]
Yes of course. You can use a `stylus` and `sass` files at the same time.
1. Add new task for sass compilation
2. Add your task to the build task
3. Add new `gulp.watch` to the watch task

ps. If you want using bootstrap it could be complicated on same page, because both gulp-front and bootstrap has same class names.
e.g. .button, .table or global styles for h1-6, p etc.
